### PR TITLE
Fix for Issue #2 - Added Wikipedia command.

### PR DESCRIPTION
**Pull request by KarlKennerley**
Added a Wikipedia command and updated the requirements.txt file.

### CODE REVIEW

**Comment by Vethya** [comment]
Hey, thanks for the contribution once again. I haven't checked the library when I assigned the issue, but it seems like this library is not working due to [this issue](https://github.com/goldsmith/Wikipedia/issues/107). I have experimented with the code and found out that another library [here](https://github.com/martin-majlis/Wikipedia-API) works. So, please change the library to the new one since it will resolve the issue.

Also, I think moving the Wikipedia command into its own file makes more sense here since it's not really a dictionary. So, making a new file called `wikipedia.py` and moving it there should be good.

**Comment by Vethya** [comment]
Hey, thanks for the changes. Unfortunately, this code is not working. Here are the problems:
- You cannot use the library directly. According to the usage guide, You have to initialize the `Wikipedia` class first before being able to call any methods.
- You forgot to use the `await` keyword at line 14 with a typo where there's a space after the '.' as well.
I can merge the pull requests after these small changes. Thank you.

**Comment by KarlKennerley** [comment]
All fixed.

**Comment by Vethya** [comment]
Alright, looks good. Thank you so much.

**Pull request merged**
