### PR TITLE
Fix for issue #3 - Added an Urban Dictionary command to query the Urban Dictionary API with word query.

### PR DESCRIPTION
**Pull request by KarlKennerley**
Added Urban Dictionary command to query the Urban Dictionary API with word query.

### CODE REVIEW

**Comment by Vethya** [comment]
Hi, Good job on the Pull request! I have a few things below that I want you to consider:
- Change the function name from `udict` to `urbandictionary`
- Move the function to a new file called `dictionary.py` (I plan to add more dictionaries in the future)
- Add 2 more aliases: `ud` and `urbandictionary` (You can keep `udict`)
- Use `edit_text` instead of `reply`
- Add more information to the message such as example, thumbs up, and thumbs down
- Lastly, There is an error encountered when you use parse_args. `join()` is actually a string method and not a list method. So, instead of `parse_args(msg).join(" ")` it should be `" ".join(parse_args(msg))`

I apologize I wasn't being specific about the issue. If you have any concerns please feel free to ask me. Thank you!

**Comment by Vethya** [comment]
@KarlKennerley Do you want me to close the pull request or do you still want to try?

**Comment by KarlKennerley** [comment]
> @KarlKennerley Do you want me to close the pull request or do you still want to try?

I'm happy to implement your suggestions. I'll crack on with them now.

**Comment by Vethya** [comment]
> I'm happy to implement your suggestions. I'll crack on with them now.

Thank you so much! Please take it easy :)

**Comment by KarlKennerley** [comment]
I've made these changes. Let me know if you have any more thoughts.
I've left dictionary.py in `userbot/plugins`. Do you want it there or moving to `userbot/plugins/utils`?

**Comment by Vethya** [comment]
> I've made these changes. Let me know if you have any more thoughts. I've left dictionary.py in `userbot/plugins`. Do you want it there or moving to `userbot/plugins/utils`?

Hey, thanks for the changes. Yes, that is good. Please leave it like that.

I believe you misunderstood, I apologize. What I mean by "Add more information to the message such as example, thumbs up, and thumbs down" is the information in the data like `definition` for example. I want the message to have the definition, example, and the number of thumbs up and thumbs down the word has.

One more thing, I noticed a typo on line 12 (`term = " ".jooin(parse_args(msg))`), you typed "o" twice there. That's all, when you fix them I can merge the pull request for you :)

**Comment by Vethya** [comment]
Thank you! I'll merge this now.

**Pull request merged**
